server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: effective-office

  profiles:
    include:
      - repository

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: band.effective.office.backend.app.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
